2024-11-25 15:26:36 +0000 - dagster - DEBUG - materialize_dbt_models - 3d95c4b2-b337-4258-87ab-fdc14ef2f172 - 3811 - LOGS_CAPTURED - Started capturing logs in process (pid: 3811).
2024-11-25 15:26:36 +0000 - dagster - DEBUG - materialize_dbt_models - 3d95c4b2-b337-4258-87ab-fdc14ef2f172 - 3811 - buy_box_gcp_1_dbt_assets - STEP_START - Started execution of step "buy_box_gcp_1_dbt_assets".
2024-11-25 15:26:36 +0000 - dagster - INFO - materialize_dbt_models - 3d95c4b2-b337-4258-87ab-fdc14ef2f172 - buy_box_gcp_1_dbt_assets - A dbt subsetted execution is not being performed. Using the default dbt selection arguments `['--select', 'fqn:*']`.
2024-11-25 15:26:38 +0000 - dagster - INFO - materialize_dbt_models - 3d95c4b2-b337-4258-87ab-fdc14ef2f172 - buy_box_gcp_1_dbt_assets - Copying `/app/buy_box_gcp_1/target/partial_parse.msgpack` to `/app/buy_box_gcp_1/target/buy_box_gcp_1_dbt_assets-3d95c4b-077a6e2/partial_parse.msgpack` to take advantage of partial parsing.
2024-11-25 15:26:38 +0000 - dagster - INFO - materialize_dbt_models - 3d95c4b2-b337-4258-87ab-fdc14ef2f172 - buy_box_gcp_1_dbt_assets - Running dbt command: `dbt build --select fqn:*`.
2024-11-25 15:26:42 +0000 - dagster - INFO - materialize_dbt_models - 3d95c4b2-b337-4258-87ab-fdc14ef2f172 - buy_box_gcp_1_dbt_assets - Finished dbt command: `dbt build --select fqn:*`.
2024-11-25 15:26:42 +0000 - dagster - ERROR - materialize_dbt_models - 3d95c4b2-b337-4258-87ab-fdc14ef2f172 - 3811 - buy_box_gcp_1_dbt_assets - STEP_FAILURE - Execution of step "buy_box_gcp_1_dbt_assets" failed.

dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command

`dbt build --select fqn:*`

failed with exit code `2`. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /app/buy_box_gcp_1/target/buy_box_gcp_1_dbt_assets-3d95c4b-077a6e2/dbt.log.

Errors parsed from dbt logs:

Encountered an error:
'dbt_bigquery://macros/adapters.sql'

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 320, in wrapper
    ctx.obj["manifest"] = parse_manifest(
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 1898, in parse_manifest
    manifest = ManifestLoader.get_full_manifest(
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 330, in get_full_manifest
    manifest = loader.load()
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 399, in load
    self.load_and_parse_macros(project_parser_files)
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 676, in load_and_parse_macros
    block = FileBlock(self.manifest.files[file_id])
KeyError: 'dbt_bigquery://macros/adapters.sql'


Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 499, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 87, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 193, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 162, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 482, in iterate_with_context
    next_output = next(iterator)
  File "/app/gcp_dagster/assets.py", line 9, in buy_box_gcp_1_dbt_assets
    yield from dbt.cli(["build"], context=context).stream()
  File "/usr/local/lib/python3.10/site-packages/dagster_dbt/core/dbt_event_iterator.py", line 203, in __next__
    return next(self._inner_iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 274, in _stream_asset_events
    for event in self.stream_raw_events():
  File "/usr/local/lib/python3.10/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 367, in stream_raw_events
    self._raise_on_error()
  File "/usr/local/lib/python3.10/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 460, in _raise_on_error
    raise error

